config/routes.rb
Rails.application.routes.draw do

  resources :topics do 
    resources :posts, except: [:index]
  end

  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic
    has_many :comments, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new
    @advertisement.title = params[:advertisement][:title]
    @advertisement.copy = params[:advertisement][:copy]
    @advertisement.price = params[:advertisement][:price]
    if @advertisement.save
      flash[:notice] = "Advertisement was saved."
      redirect_to @advertisement
    else
      flash.now[:alert] = "There was an error saving the advertisement.  Please try again."
      render :new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])
    @post.topic = @topic    
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post.  Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions = Question.all
    end
    
    def show
        @question = Question.find(params[:id])
    end

    def new
        @question = Question.new
    end
    
    def create
        @question = Question.new
        @question.title = params[:question][:title]
        @question.body = params[:question][:body]
        @question.resolved = params[:question][:resolved]
        
        if @question.save
          flash[:notice] = "Question was saved."
          redirect_to @question
        else
          flash.now[:alert] = "There was an error saving the question.  Please try again."
          render :new
        end
    end
    
    def edit
        @question = Question.find(params[:id])
    end
    
    def update
        @question = Question.find(params[:id])
        @question.title = params[:question][:title]
        @question.body = params[:question][:body]
        @question.resolved = params[:question][:resolved]
        if @question.save
          flash[:notice] = "Question was updated."
          redirect_to @question
        else
          flash.now[:alert] = "There was an error saving the question. Please try again."
          render :edit
        end
    end

    def destroy
        @question = Question.find(params[:id])
        if @question.destroy
          flash[:notice] = "\"#{@question.title}\" was deleted successfully."
          redirect_to questions_path
        else
          flash.now[:alert] = "There was an error deleting the question."
          render :show
        end
    end    
   
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        @topics = Topic.all
    end
    
    def show
      @topic = Topic.find(params[:id])
    end    
 
    def new
      @topic = Topic.new
    end    

   def create
     @topic = Topic.new
     @topic.name = params[:topic][:name]
     @topic.description = params[:topic][:description]
     @topic.public = params[:topic][:public]
 
     if @topic.save
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash.now[:alert] = "Error creating topic. Please try again."
       render :new
     end
   end
   
   def edit
       @topic = Topic.find(params[:id])
   end
   
    def update
     @topic = Topic.find(params[:id])
 
     @topic.name = params[:topic][:name]
     @topic.description = params[:topic][:description]
     @topic.public = params[:topic][:public]
 
     if @topic.save
        flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash.now[:alert] = "Error saving topic. Please try again."
       render :edit
     end
    end
   
    def destroy
     @topic = Topic.find(params[:id])
 
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
    end
   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
  def contact
  end
  
  def faq
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/create.html.erb
<h1>Advertisements#create</h1>
<p>Find me in app/views/advertisements/create.html.erb</p>

app/views/advertisements/index.html.erb
<h1>Advertisements#index</h1>
<p>Find me in app/views/advertisements/index.html.erb</p>
<h1>All Advertisements</h1>
<% @advertisements.each do | ad | %>
    <p><span>Ad Title: </span><%= ad.title %></p>
    <p><span>Ad Copy: </span><%= ad.copy %></p>
    <p><span>Ad Price: $</span><%= ad.price %></p>
<% end %>

app/views/advertisements/new.html.erb
<h1>Advertisements#new</h1>
<p>Find me in app/views/advertisements/new.html.erb</p>

<h1>New Advertisement</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for advertisements</p>
        <ul>
            <li>Only good products</li>
            <li>Only funny ads</li>
            <li>Only free products</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @advertisement do |a| %>
            <div class="form-group">
                <%= a.label :title %>
                <%= a.text_field :title, class: 'form-control', placeholder: "Enter advertisement title" %>
            </div>
            <div class="form-group">
                <%= a.label :copy %>
                <%= a.text_area :copy, rows: 8, class: 'form-control', placeholder: "Enter advertisement copy" %>     
            </div>
            <div class="form-group">
                <%= a.label :price %>
                <%= a.text_field :price, rows: 8, class: 'form-control', placeholder: "Enter price" %>     
            </div>
            <div class="form-group">
                <%= a.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/advertisements/show.html.erb
<h1>Advertisements#show</h1>
<p>Find me in app/views/advertisements/show.html.erb</p>
<h1>Title: <%= @advertisement.title %></h1>
<p>Copy: <%= @advertisement.copy %></p>
<p>Price: $<%= @advertisement.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccit</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Bloccit", root_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<h1>Edit Post</h1>
 
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
           <li>Make sure it rhymes.</li>
           <li>Don't use the letter "A".</li>
           <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for [@post.topic, @post] do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>


<h1>New Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for [@topic, @post] do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>     
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
 
<div class="row">
    <div class="col-md-8">
        <p><%= @post.body %></p>
    </div>
    <div class="col-md-4">
         <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
         <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    </div>
</div>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>
<h1>Edit Questions</h1>
 
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for questions</p>
        <ul>
           <li>Make sure it looks like a duck.</li>
           <li>Don't let it quack too loudly.</li>
           <li>The incessant use of quackers will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
            </div>
            <div class="form-group">
                <%= f.label :resolved %>
                <%= f.check_box :resolved %>     
            </div>               
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>
<h1>All Questions</h1>
<% @questions.each do |question| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to question.title, question %>
            </h4>
        </div>
    </div>
<% end %>

app/views/questions/new.html.erb
<h1>Question#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>


<h1>New Question</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for questions</p>
        <ul>
            <li>Make sure it asks please.</li>
            <li>Don't use the letter "Q".</li>
            <li>The incessant use of red caps will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>     
            </div>
            <div class="form-group">
                <p>Resolved?</p>
                <%= f.check_box :resolved, class: 'form-control' %>     
            </div>            
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
 
<div class="row">
    <div class="col-md-8">
        <p><%= @question.body %></p>
        <p>Resolved: <%= @question.resolved %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
        <%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this question?'} %>
    </div>
</div>

app/views/topics/edit.html.erb
 <h1>Edit Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">

         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
 <h1>Topics</h1>
 
 <div class="row">
   <div class="col-md-8">

     <% @topics.each do |topic| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">

             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">

     <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/topics/new.html.erb
 <h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
 <h1><%= @topic.name %></h1>
 
 <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>
     <% @topic.posts.each do |post| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to post.title, topic_post_path(@topic, post) %>
           </h4>
           <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago <br>
             <%= post.comments.count %> Comments
           </small>          
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>
<!-- <button class="social-btn"><%= link_to "My LinkedIn Page", "https://www.linkedin.com/in/ken-carbullido-70244a13" %></button>  -->

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>